//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coder
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsmissions
    {
        public int id { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<int> state { get; set; }
        public int task_id { get; set; }
        public string output { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tasks tasks { get; set; }
        public virtual users users { get; set; }
    }
}
