//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coder
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.subsmissions = new HashSet<subsmissions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> admin { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string ssn { get; set; }
        public string created { get; set; }
        public Nullable<bool> gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subsmissions> subsmissions { get; set; }
    }
}
