//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderUi
{
    using System;
    using System.Collections.Generic;

   
    public partial class Assignment
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int value { get; set; }
        public string status { get; set; }
        public string courseName { get; set; }
        public string start { get; set; }
        public string end { get; set; }

        public List<Assignment> getAssignments()
        {
          
            Assignment as1 = new Assignment { Id = 1,status = "incomplete", name = "Something1", description = "LoremIpsum", value = 80, courseName = "Gagnaskipan", start = "28.04.16", end = "04.05.16" };
            Assignment as2 = new Assignment { Id = 1,status = "incomplete", name = "Something2", description = "LoremIpsum", value = 20, courseName = "Gagnaskipan", start = "30.04.16", end = "04.05.16" };
            Assignment as3 = new Assignment { Id = 1,status = "incomplete", name = "Something3", description = "LoremIpsum", value = 33, courseName = "Gagnaskipan", start = "30.04.16", end = "04.05.16" };
            Assignment as4 = new Assignment { Id = 1,status = "incomplete", name = "Something4", description = "LoremIpsum", value = 50, courseName = "Gagnaskipan", start = "01.06.16", end = "8.06.16" };
            Assignment as5 = new Assignment { Id = 1,status = "incomplete", name = "Something5", description = "LoremIpsum", value = 60, courseName = "Gagnaskipan", start = "14.05.16", end = "20.05.16" };
            Assignment as6 = new Assignment { Id = 1,status = "incomplete", name = "Something6", description = "LoremIpsum", value = 70, courseName = "Gagnaskipan", start = "02.05.16", end = "10.05.16" };
            Assignment as7 = new Assignment { Id = 1,status = "incomplete", name = "Something7", description = "LoremIpsum", value = 100, courseName = "Gagnaskipan", start = "01.06.16", end = "8.06.16" };
            Assignment as8 = new Assignment { Id = 1,status = "incomplete", name = "Something8", description = "LoremIpsum", value = 80, courseName = "Gagnaskipan", start = "14.05.16", end = "20.05.16" };
            Assignment as9 = new Assignment { Id = 1,status = "incomplete", name = "Something9", description = "LoremIpsum", value = 10, courseName = "Gagnaskipan", start = "02.05.16", end = "10.05.16" };
            Assignment as10 = new Assignment {Id = 1,status = "incomplete", name = "Something10", description = "LoremIpsum", value = 33, courseName = "Gagnaskipan", start = "02.05.16", end = "10.05.16" };

            List<Assignment> benni = new List<Assignment>();
            benni.Add(as1);
            benni.Add(as2);
            benni.Add(as3);
            benni.Add(as4);
            benni.Add(as5);
            benni.Add(as6);
            benni.Add(as7);
            benni.Add(as8);
            benni.Add(as9);
            benni.Add(as10);           

            return benni;
        }
    }
}
